services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    image: with-docker-multi-env-development
    ports:
      - "3001:3000"
    volumes:
      - ${IMAGE_UPLOADS_DIRECTORY}:/app/public/uploads
