services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    image: with-docker-multi-env-production
    ports:
      - "3003:3000"
    volumes:
      - ${IMAGE_UPLOADS_DIRECTORY}:/app/public/uploads
