services:
  app:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    image: gopicky-image-app
    ports:
      - "3003:3000"
    volumes:
      - ${IMAGE_UPLOAD_DIR}:/app/uploads
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ${DB_DATADIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
  cleanup:
    build:
      context: ../../
      dockerfile: docker/cleanup/Dockerfile
    image: gopicky-image-cleanup
    volumes:
      - ${IMAGE_UPLOAD_DIR}:/uploads
