services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    image: with-docker-multi-env-production
    ports:
      - "3003:3000"
    volumes:
      - ${IMAGE_UPLOAD_DIR}:/app/public/uploads
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ${DB_DATADIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
